### ISSUE TITLE
Finish math classes for 2D development

### ISSUE THREAD

**Issue by Squeakrats** [mjneil/CruftEngine#5]
We need vec2 and mat3 fully implemented before we can do any kind of 2D 
graphics, physics, or networking.

**Comment by katamaritaco** [comment]
:exclamation: Added a checklist here:
- [x] vec2
- [ ] vec3
- [x] mat3

**Comment by katamaritaco** [comment]
Which ones were finished @mjneil ?

**Comment by Squeakrats** [comment]
I believe both are complete (aside from anything we randomly might need)
