### ISSUE TITLE
Document and test  files in engine/core. 

### ISSUE THREAD

**Issue by Squeakrats** [mjneil/CruftEngine#7]
- [ ] Actor.js
- [ ] Component.js
- [ ] ActorFactory.js
- [ ] Scheduler.js
- [ ] MemoryManager.js
- [ ] Process.js
- [ ] Cache.js
- [ ] Referencable.js

**Comment by katamaritaco** [comment]
It'd be nice if you made those into checkboxes:

https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

**Comment by Squeakrats** [comment]
Oooh thank

**Comment by LOZORD** [comment]
Would you guys also want coverage?

**Comment by Squeakrats** [comment]
Coverage?

**Comment by LOZORD** [comment]
Yeah! Coverage == what is covered by tests. This is a really good library for doing so: https://github.com/gotwarlost/istanbul .

**Comment by Squeakrats** [comment]
I like it just because of the name. No this seems really cool. I'll look into it

**Comment by mjneil** [comment]
Looks crufty.

**Comment by LOZORD** [comment]
@mjneil Is that a good thing given the name of this project? :trollface:

**Comment by katamaritaco** [comment]
I thought McNeil was doing tests by hand?

Also the name is gr8

Get Outlook for Androidhttp://aka.ms/ghei36

On Fri, Feb 26, 2016 at 12:40 PM -0800, "Leo Rudberg" <notifications@github.com<mailto:notifications@github.com>> wrote:

@mjneilhttps://github.com/mjneil Is that a good thing given the name of this project? [:trollface:]

##

**Comment by mjneil** [comment]
@LOZORD no, I wasn't making a pun. We are actually going for least amount of cruft. I don't fully understand the benefit this would give us. Shouldn't just add things cause the name is cool

**Comment by LOZORD** [comment]
It basically tells you what you need to test. I liked using it at work this
summer. Don't need it if you don't want it.

**Comment by mjneil** [comment]
Not saying don't want it, just didn't understand the benefit it brings

**Comment by Squeakrats** [comment]
thanks Leo! I just added it to the project. I'll close this issue and just track it in there.
